Repository syntax-tree/unist-util-visit, pull requests merged in 2021-07, with the labels that each got.

#27 Update `readme.md`
  readme.md
Labels: 👋 phase/new, 📚 area/docs

#28 Update tests for changes in `@types/unist`
  test.js
Labels: 🤞 phase/open

#29 Change types to base what `visitor` gets on `tree`
  index.js
  index.test-d.ts
  package.json
Labels: ☂️ area/types, 👍 phase/yes, 🦋 type/enhancement, 🧑 semver/major
